version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: stock-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: stockdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - stock-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: stockdb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password123
    depends_on:
      - mongodb
    networks:
      - stock-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - stock-network

volumes:
  mongodb_data:

networks:
  stock-network:
    driver: bridge
